### ISSUE TITLE
Request for MS- and Pan-kernels for WV2 sensor

### ISSUE THREAD

**Issue by KSJhon** [ChengJin-git/LPPN#2]
Dear Jin!
Thank you for your nice work.
Recently, for fair comparison, I am trying to train your code for WV2 sensor image, but corresponding kernels is not provided.
Is it possible to share these files?

Kind regards.

**Comment by ChengJin-git** [comment]
Hi,
Sorry for the late reply. Our team currently is working on ECCV conference in March. I would commit the generation file of the MTF kernel and its corresponding description tonight. So stay tuned for the file!

**Comment by ChengJin-git** [comment]
Hi,
We've uploaded the generation script of the MTF kernels. You may use it to generate the related WV2 kernels.

**Comment by KSJhon** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thanks for your kind help.I have checked your code generates the same results as your paper.Best regards.
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    On 2/27/2022 17:16，Cheng ***@***.***> wrote： 



Hi,
We've uploaded the generation script of the MTF kernels. You may use it to generate the related WV2 kernels.
