### ISSUE TITLE
normalizaition scale

### ISSUE THREAD

**Issue by AbigNuiZy** [ChengJin-git/LPPN#3]

**Comment by ChengJin-git** [comment]
您好，因为邮箱设置到非常用邮箱没能及时回复您的 issue，非常抱歉！

QuickBird 和 GF-2 分别是 11 和 10 位，再次抱歉未能及时回复！


________________________________
发件人: AbigNuiZy ***@***.***>
发送时间: 2022年12月4日 15:17
收件人: ChengJin-git/LPPN ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ChengJin-git/LPPN] normalizaition scale (Issue #3)


您好，我刚刚要入门遥感图像融合，请问how-to-run里面的“Change the normalizaition scale according to the worldview level of the corresponding datasets”的normalizaition scale是什么？worldView是11那么QuickBird和GF-2的是什么。恭候您的答复。

―
